"""
AI and RAG (Retrieval-Augmented Generation) Services Pipeline.
Handles LLM initialization, vector database connections, and generation of literary insights.
"""
import os
import json
import chromadb

from langchain_huggingface import HuggingFaceEmbeddings, HuggingFaceEndpoint, ChatHuggingFace
from langchain_chroma import Chroma

# ==========================================
# 1. MODEL & VECTOR DB INITIALIZATION
# ==========================================

# We use Qwen 2.5 7B Instruct because it excels at following structural JSON instructions 
# without requiring heavy, expensive gated models like GPT-4.
llm_endpoint = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct", 
    task="text-generation",
    temperature=0.3,       # Low temperature for deterministic, analytical outputs
    max_new_tokens=1500,   # High limit to accommodate 500-word summaries
    do_sample=False
)
llm = ChatHuggingFace(llm=llm_endpoint)

# Initialize lightweight local embeddings to save on API costs and maintain data privacy.
hf_embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# Connect to the local ChromaDB instance containerized in the backend
chroma_client = chromadb.HttpClient(host=os.environ.get('CHROMA_HOST', 'chromadb'), port=8000)
vector_store = Chroma(
    client=chroma_client, 
    collection_name="markdown_hf_chunks", 
    embedding_function=hf_embeddings
)

# ==========================================
# 2. CORE AI FUNCTIONS
# ==========================================

def generate_book_insights(book_id, book_title):
    """
    Retrieves book chunks from the vector store and generates a structured literary analysis.
    
    Args:
        book_id (int): The primary key of the book in the relational database.
        book_title (str): The title of the book to provide context to the LLM.
        
    Returns:
        dict: A dictionary containing 'summary', 'genre', and 'sentiment'.
    """
    query = f"What is the main plot, ending, genre, and emotional tone of {book_title}?"
    docs = vector_store.similarity_search(query, k=6, filter={"book_id": book_id})
    
    if not docs:
        return {
            "summary": "Insufficient data in vector store to generate insights.", 
            "genre": "Unknown", 
            "sentiment": "Neutral"
        }

    context = "\n\n".join([doc.page_content for doc in docs])

    # We avoid LangChain's JSON parsers here because heavy hidden instructions
    # can confuse smaller 7B models. An explicit, hardcoded prompt yields much higher reliability.
    prompt = f"""Act as an expert literary analyst. You must analyze the excerpts from '{book_title}' and return your analysis STRICTLY as a valid JSON object. Do not include any text outside the JSON.

Excerpts:
{context}

INSTRUCTIONS FOR THE JSON VALUES:
1. "summary": Write a comprehensive summary strictly between 300 and 500 words. You MUST explicitly use Markdown formatting (use ### for section headers, **bolding** for character names, and bullet points). Detail the inciting incident, character developments, climax, and resolution. Use \\n for line breaks. Do NOT include the genre or sentiment in this field.
2. "genre": State the primary genre in maximum 3 words.
3. "sentiment": State the overall emotional tone in maximum 3 words.

You must return EXACTLY this format and nothing else:
{{
    "summary": "your markdown summary here...",
    "genre": "your genre here",
    "sentiment": "your sentiment here"
}}"""
    
    try:
        response = llm.invoke(prompt)
        content = response.content.strip()
        
        # Defensive parsing: LLMs frequently wrap JSON in markdown blocks despite instructions.
        # We aggressively strip these out before passing to Python's json.loads parser.
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
            
        start_idx = content.find('{')
        end_idx = content.rfind('}') + 1
        clean_json = content[start_idx:end_idx]
        
        # strict=False allows the JSON parser to natively handle unescaped \n characters,
        # which is essential for preserving the Markdown formatting generated by the LLM.
        return json.loads(clean_json, strict=False)
        
    except Exception as e:
        print(f"\n[🚨 AI PARSING ERROR] Failed for {book_title}! Details: {str(e)}")
        return {
            "summary": "### Generation Error\n\nThe AI model failed to format the response correctly. Please check backend logs.", 
            "genre": "Error", 
            "sentiment": "Error"
        }


def get_recommendations(book_id, book_title):
    """
    Generates basic book recommendations using vector similarity.
    Instead of an expensive LLM call, we query ChromaDB for chunks that 
    share similar semantic themes to the current book's title.
    """
    docs = vector_store.similarity_search(book_title, k=5)
    
    # Use a set comprehension to extract unique titles, ensuring we don't recommend the current book
    recommended = {
        doc.metadata.get('title') 
        for doc in docs 
        if doc.metadata.get('title') and doc.metadata.get('title') != book_title
    }
    
    recs = list(recommended)[:2]
    if recs:
        return f"If you liked {book_title}, you'll likely enjoy: {', '.join(recs)}."
    return "Not enough data yet to form a recommendation."


def stream_rag_query(question, book_id=None):
    """
    Core RAG Q&A Engine.
    Retrieves context from ChromaDB and yields the LLM's response token-by-token 
    to support Server-Sent Events (SSE) for a smooth, real-time typing effect on the frontend.
    """
    filter_dict = {"book_id": book_id} if book_id else None
    
    # Limit retrieval to top 4 chunks to avoid overwhelming the LLM context window
    docs = vector_store.similarity_search(question, k=4, filter=filter_dict)
    
    if not docs:
        yield "I couldn't find enough information in the book to answer that."
        return

    # Inject source metadata directly into the context so the LLM can cite its findings
    context = "\n\n".join([f"Source: {doc.metadata.get('title', 'Unknown')}\n{doc.page_content}" for doc in docs])
    
    prompt = (
        "You are an intelligent library assistant. Use the provided context to answer the user's question. "
        "Include citations by referencing the 'Source'. \n"
        "IMPORTANT: You MUST format your entire response using rich Markdown (bolding, bullet points, headers).\n\n"
        f"Context:\n{context}\n\nQuestion: {question}"
    )
    
    # Bypass the standard `.invoke()` and stream directly for UI responsiveness
    for chunk in llm.stream(prompt):
        yield chunk.content