"""
API Views for the Document Intelligence Platform.
Handles standard CRUD operations, caching, lazy-loading of AI insights,
and Server-Sent Events (SSE) streaming for the RAG chat interface.
"""
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.http import StreamingHttpResponse

from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Book, BookInsight
from .serializers import BookListSerializer, BookDetailSerializer
from .ai_services import generate_book_insights, stream_rag_query, get_recommendations


class BookListCreateView(generics.ListCreateAPIView):
    """
    Retrieves a paginated list of all books.
    Uses a lightweight serializer to avoid transmitting heavy HTML payloads to the dashboard.
    """
    queryset = Book.objects.all().order_by('-id')

    def get_serializer_class(self):
        # Optimize the GET request payload for the frontend grid
        if self.request.method == 'GET':
            return BookListSerializer
        return BookDetailSerializer

    @method_decorator(cache_page(60 * 15))
    def get(self, request, *args, **kwargs):
        # Cache the dashboard for 15 minutes to handle high traffic efficiently without database hits
        return super().get(request, *args, **kwargs)


class BookDetailView(generics.RetrieveAPIView):
    """
    Retrieves full book details and lazily generates AI insights on-demand.
    """
    queryset = Book.objects.all()
    serializer_class = BookDetailSerializer

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        
        # Fetch or initialize the 1:1 insight relationship
        insight, created = BookInsight.objects.get_or_create(book=instance)
        
        # Lazy-loading pattern: We only invoke the expensive LLM call if the data is missing.
        # This prevents the bulk ingestion script from taking hours to process insights during scraping.
        missing_summary = not insight.summary or insight.summary in ["Failed.", "Insufficient data.", "No summary generated."]
        
        if created or missing_summary:
            insights_data = generate_book_insights(instance.id, instance.title)
            
            insight.summary = insights_data.get("summary", "No summary generated.")
            insight.genre = insights_data.get("genre", "Unknown")
            insight.sentiment = insights_data.get("sentiment", "Unknown")
            insight.save() 
            
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


class BookRecommendationView(APIView):
    """
    Provides book recommendations utilizing semantic vector similarity search.
    """
    def get(self, request, pk):
        try:
            book = Book.objects.get(pk=pk)
            return Response({
                "target_book": book.title,
                "recommendation": get_recommendations(book.id, book.title)
            }, status=status.HTTP_200_OK)
        except Book.DoesNotExist:
            return Response({"error": "Book not found."}, status=status.HTTP_404_NOT_FOUND)


class BookRAGQueryView(APIView):
    """
    Handles context-aware user queries regarding specific books.
    Streams the LLM response back to the client using Server-Sent Events (SSE).
    """
    def post(self, request):
        question = request.data.get('question')
        book_id = request.data.get('book_id')
        
        if not question:
            return Response({"error": "Question is required."}, status=status.HTTP_400_BAD_REQUEST)

        def event_stream():
            # Yield tokens as they are generated by the Hugging Face model
            for chunk in stream_rag_query(question, book_id):
                # Escape newlines to prevent breaking the strict SSE protocol format
                formatted_chunk = chunk.replace('\n', '\\n') 
                yield f"data: {formatted_chunk}\n\n"
                
        return StreamingHttpResponse(event_stream(), content_type='text/event-stream')