# Generated by Django 4.2.30 on 2026-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official title of the book.', max_length=255)),
                ('author', models.CharField(help_text='The primary author or authors of the book.', max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average user rating (e.g., 4.50). Extracted from the source site.', max_digits=3, null=True)),
                ('reviews_count', models.IntegerField(blank=True, help_text='Total number of user reviews or ratings the book has received.', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed synopsis, summary, or back-cover text of the book.', null=True)),
                ('book_url', models.URLField(help_text="The direct URL to the book's page on the scraped website. Used to uniquely identify and prevent duplicate scrapes.", max_length=700, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The exact date and time this book record was first scraped and added to the database.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this book record was last updated (e.g., if ratings or review counts change).')),
            ],
        ),
    ]
