# Generated by Django 4.2.30 on 2026-04-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Extracted cover image.', null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='html_content',
            field=models.TextField(blank=True, help_text='Raw HTML content extracted from the ZIP.', null=True),
        ),
    ]
