# Generated by Django 5.2.13 on 2026-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image_book_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(help_text="The direct URL to the book's page on the scraped website. Used to uniquely identify and prevent duplicate scrapes.", max_length=255, unique=True),
        ),
    ]
