# Generated by Django 5.2.13 on 2026-04-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinsight',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookinsight',
            name='sentiment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
